"""Claim Attachments — DOCTYPE Source-to-Destination Audit (v7).

Deterministic verification that the documents processed from the HBSys
source grid correspond correctly to the files created under:

    C:\\Shared Folder\\eClaimsDoc\\<CLAIM_SERIES_NUMBER>\\

Verification inputs (all EXISTING values — nothing is re-derived):
    1. SOURCE PROCESSING ORDER — a per-claim-series sequence number
       ("01", "02", ...) assigned at the moment the automation copies
       each source full path from the HBSys grid (inside the existing
       v6.1 tab-walk loop; never re-generated by sorting).
    2. EXTRACTED DOCTYPE — the EXISTING `file_docs[matched_file]` value
       from `core.claim_attachments_doc_type.detect_doc_type` (mapping
       untouched; this module only CONSUMES the result).
    3. CLAIM SERIES NUMBER — the EXISTING value parsed from the
       attachment popup title (`extract_claim_series_from_title`).
    4. ACTUAL DESTINATION FILENAMES — filesystem entries of the claim
       series folder, parsed deterministically:

           ...-RAW-<DOCTYPE>-<NUMBER>.<ext>
               DOH-PDFA-1b-RAW-CF4-08.xml -> doctype "CF4", number "08"

NO OCR. NO screenshot/image reading. NO UI readback. NO AI/fuzzy
matching. The destination FILENAME is the only verification source for
the destination DOCTYPE and sequence number (replacing the v6.2 OCR
readback, which produced many REVIEW - READ_FAILED results).

Results (never guessed, never hidden):
    MATCH                source number + doctype == destination number
                         + doctype
    MISMATCH            destination missing for a source number, or
                         DOCTYPE mismatch, or duplicate destination
                         number
    UNEXPECTED DEST.    destination number with no source record
    REVIEW              claim series folder missing, or a destination
                         filename that cannot be parsed

Excel report: records are collected in memory during the batch; the
destination comparison runs ONCE per claim series AFTER its documents
finish (single folder scan); the report is generated ONCE after the
whole batch finishes, then opened with the default Windows Excel
behavior (os.startfile).
"""

from __future__ import annotations

import os
import re
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Optional

# Destination root for uploaded eClaims documents (owner-provided).
ECLAIMS_DOC_ROOT = Path(r"C:\Shared Folder\eClaimsDoc")

# Audit statuses (exact report vocabulary)
STATUS_MATCH = "MATCH"
STATUS_MISMATCH = "MISMATCH"
STATUS_REVIEW = "REVIEW"
STATUS_UNEXPECTED = "UNEXPECTED DESTINATION"

# Destination naming pattern (deterministic, generic — no hardcoded
# doc-type list):
#     DOH-PDFA-1b-RAW-CSF-01.pdf   -> doctype CSF, number 01
#     DOH-PDFA-1b-RAW-CF4-08.xml   -> doctype CF4, number 08
# The doctype token is 2-4 letters/digits directly after the LAST
# "RAW-" marker; the number is the trailing 1-3 digit token before the
# extension.
_DEST_RE = re.compile(r"-RAW-([A-Za-z0-9]{2,4})-(\d{1,3})$")


def normalize_doctype(value: Optional[str]) -> str:
    """Deterministic minimal normalization for the final comparison.

    Handles harmless differences only (" csf " / "CSF" / None); never
    treats different doc values as equal.
    """
    if value is None:
        return ""
    return str(value).strip().upper()


def normalize_sequence(value: Optional[str]) -> str:
    """Normalize a sequence number so "01" == "1" == 1 logically.

    Comparison uses the int value; the ORIGINAL display value is kept
    in the record/report (task §21).
    """
    if value is None:
        return ""
    digits = str(value).strip()
    try:
        return str(int(digits))
    except ValueError:
        return digits


def extract_claim_series_from_title(title: str) -> str:
    """Claim/series number from an HBSys attachment popup title.

    Reuses the popup title the workflow already depends on (no second
    claim-number extraction mechanism):
        'Attachments for ANDAYA, FERNANDO OROLA - 260907095364'
            -> '260907095364'
    Returns '' when the title carries no trailing number.
    """
    if not title:
        return ""
    match = re.search(r"(\d{6,})\s*$", title.strip())
    return match.group(1) if match else ""


# -- source records ---------------------------------------------------------


@dataclass
class SourceAuditRecord:
    """One document's source audit entry (kept in memory).

    Created immediately after the existing workflow copied the source
    full path and extracted the DOCTYPE — the sequence number is the
    ACTUAL processing order inside the current claim series, never
    re-derived from filenames or Explorer ordering.
    """

    source_number: str          # per-claim-series sequence "01", "02", ...
    claim_series_number: str    # from the popup title (existing value)
    source_filename: str
    source_full_path: str
    extracted_doctype: str      # EXISTING extraction result (consumed)
    timestamp: str


class SourceAuditCollector:
    """Per-batch collector with per-claim-series source sequencing.

    One collector per operator; `start_series()` resets the source
    sequence to 01 for each claim series (task §7 — the destination
    files are numbered per claim series, so the source sequence must
    restart with each one).
    """

    def __init__(self) -> None:
        self.records: list[SourceAuditRecord] = []
        self._series_count = 0
        self._current_series = ""

    def start_series(self, claim_series_number: str) -> None:
        """Begin a new claim series — next record is number 01."""
        self._series_count = 0
        self._current_series = claim_series_number or ""

    def add(
        self,
        source_full_path: str,
        extracted_doctype: str,
        claim_series_number: str = "",
    ) -> SourceAuditRecord:
        """Record one processed source document.

        The claim series argument is optional; the collector falls back
        to the series of the current `start_series()` (both come from
        the same existing popup-title value).
        """
        self._series_count += 1
        record = SourceAuditRecord(
            source_number=f"{self._series_count:02d}",
            claim_series_number=claim_series_number or self._current_series,
            source_filename=Path(source_full_path).name,
            source_full_path=source_full_path,
            extracted_doctype=extracted_doctype,
            timestamp=f"{datetime.now():%Y-%m-%d %H:%M:%S}",
        )
        self.records.append(record)
        return record


# -- destination parsing ----------------------------------------------------


@dataclass
class DestinationFile:
    """One parsed destination file entry from the claim series folder."""

    filename: str
    full_path: str
    doctype: str               # '' when unparseable
    number: str                # '' when unparseable (display form)
    parsed: bool


def parse_destination_filename(filename: str) -> tuple[str, str, bool]:
    """Parse '...-RAW-<DOCTYPE>-<NUMBER>' from a destination filename.

    Returns (doctype, number, parsed):
        DOH-PDFA-1b-RAW-CF4-08.pdf -> ("CF4", "08", True)
        DOH-PDFA-1b-RAW-CSF-01.pdf -> ("CSF", "01", True)
        anything else              -> ("", "", False)

    Deterministic regex only — no vocabulary hardcoding, no OCR, no
    fuzzy matching. The extension (pdf/xml/...) is irrelevant here.
    """
    base = str(filename).strip()
    if "." in base:
        base = base.rsplit(".", 1)[0]  # drop the extension
    match = _DEST_RE.search(base)
    if not match:
        return "", "", False
    return match.group(1).upper(), match.group(2), True


def scan_destination_folder(
    folder: Path,
) -> Optional[list[DestinationFile]]:
    """List and parse the files in one claim series destination folder.

    Returns None when the folder does not exist (caller records REVIEW
    — never crashes the batch). Subdirectories are ignored.
    """
    if not folder.is_dir():
        return None
    entries: list[DestinationFile] = []
    for entry in sorted(folder.iterdir()):
        if not entry.is_file():
            continue
        doctype, number, parsed = parse_destination_filename(entry.name)
        entries.append(
            DestinationFile(
                filename=entry.name,
                full_path=str(entry),
                doctype=doctype,
                number=number,
                parsed=parsed,
            )
        )
    return entries


# -- audit results ----------------------------------------------------------


@dataclass
class AuditResult:
    """One row of the final source-to-destination audit report."""

    status: str                         # MATCH | MISMATCH | REVIEW | UNEXPECTED DESTINATION
    reason: str
    claim_series_number: str
    source_number: str
    source_filename: str
    source_full_path: str
    extracted_doctype: str
    destination_number: str
    destination_filename: str
    destination_full_path: str
    destination_doctype: str
    timestamp: str


@dataclass
class SeriesAudit:
    """Audit outcome for one claim series (built by audit_claim_series)."""

    claim_series_number: str
    results: list[AuditResult] = field(default_factory=list)
    folder_missing: bool = False


def audit_claim_series(
    records: list[SourceAuditRecord],
    claim_series_number: str,
    dest_root: Path = ECLAIMS_DOC_ROOT,
) -> SeriesAudit:
    """Compare one claim series' source records with its destination.

    Deterministic rules (task §12–§20):
        - destination entries are keyed by their FILENAME sequence
          number (never Explorer order, never mtime);
        - source number N matches destination number N AND the
          normalized DOCTYPEs must be equal -> MATCH;
        - missing destination number -> MISMATCH "Destination file not
          found";
        - same number but different DOCTYPE -> MISMATCH "DOCTYPE
          mismatch";
        - duplicate destination numbers -> MISMATCH "Duplicate
          destination sequence number" (never silently chosen);
        - destination number with no source record -> UNEXPECTED
          DESTINATION;
        - unparseable destination filename -> REVIEW "Unable to parse
          destination filename";
        - missing claim series folder -> one REVIEW record "Claim
          Series destination folder not found" (batch continues).
    """
    audit = SeriesAudit(claim_series_number=claim_series_number)
    series_records = [
        r for r in records if r.claim_series_number == claim_series_number
    ]
    now = f"{datetime.now():%Y-%m-%d %H:%M:%S}"

    folder = Path(dest_root) / claim_series_number
    entries = scan_destination_folder(folder)
    if entries is None:
        audit.folder_missing = True
        if series_records:
            audit.results.append(
                AuditResult(
                    status=STATUS_REVIEW,
                    reason="Claim Series destination folder not found",
                    claim_series_number=claim_series_number,
                    source_number="",
                    source_filename="",
                    source_full_path="",
                    extracted_doctype="",
                    destination_number="",
                    destination_filename="",
                    destination_full_path=str(folder),
                    destination_doctype="",
                    timestamp=now,
                )
            )
        return audit

    # Group destination entries by normalized sequence number.
    by_number: dict[str, list[DestinationFile]] = {}
    for entry in entries:
        if not entry.parsed:
            continue  # handled below as REVIEW
        by_number.setdefault(normalize_sequence(entry.number), []).append(entry)

    # Per-source comparison (processing order preserved).
    for record in series_records:
        key = normalize_sequence(record.source_number)
        candidates = by_number.get(key)

        if candidates is None:
            audit.results.append(
                _result(
                    STATUS_MISMATCH,
                    "Destination file not found",
                    record,
                    now,
                )
            )
            continue

        if len(candidates) > 1:
            # Duplicate destination sequence number — never silently
            # choose one; list every candidate in the reason.
            names = ", ".join(c.filename for c in candidates)
            first = candidates[0]
            audit.results.append(
                _result(
                    STATUS_MISMATCH,
                    f"Duplicate destination sequence number ({names})",
                    record,
                    now,
                    destination=first,
                )
            )
            continue

        dest = candidates[0]
        if normalize_doctype(record.extracted_doctype) != normalize_doctype(
            dest.doctype
        ):
            audit.results.append(
                _result(
                    STATUS_MISMATCH,
                    "DOCTYPE mismatch",
                    record,
                    now,
                    destination=dest,
                )
            )
        else:
            audit.results.append(
                _result(STATUS_MATCH, "", record, now, destination=dest)
            )

    # Unexpected destinations: numbers with no source record.
    source_numbers = {
        normalize_sequence(r.source_number) for r in series_records
    }
    for key, candidates in sorted(by_number.items()):
        if key in source_numbers:
            continue
        for dest in candidates:
            audit.results.append(
                _result(
                    STATUS_UNEXPECTED,
                    "Destination document has no corresponding source record",
                    None,
                    now,
                    destination=dest,
                    series=claim_series_number,
                )
            )

    # Unparseable destination filenames — REVIEW, never guessed.
    for entry in entries:
        if not entry.parsed:
            audit.results.append(
                _result(
                    STATUS_REVIEW,
                    "Unable to parse destination filename",
                    None,
                    now,
                    destination=entry,
                    series=claim_series_number,
                )
            )

    return audit


def _result(
    status: str,
    reason: str,
    record: Optional[SourceAuditRecord],
    timestamp: str,
    destination: Optional[DestinationFile] = None,
    series: str = "",
) -> AuditResult:
    """Build one AuditResult row from a source record and/or destination."""
    return AuditResult(
        status=status,
        reason=reason,
        claim_series_number=(record.claim_series_number if record else series),
        source_number=(record.source_number if record else ""),
        source_filename=(record.source_filename if record else ""),
        source_full_path=(record.source_full_path if record else ""),
        extracted_doctype=(record.extracted_doctype if record else ""),
        destination_number=(destination.number if destination else ""),
        destination_filename=(destination.filename if destination else ""),
        destination_full_path=(destination.full_path if destination else ""),
        destination_doctype=(destination.doctype if destination else ""),
        timestamp=timestamp,
    )


# -- Excel report ----------------------------------------------------------

_REPORT_COLUMNS = [
    "Status",
    "Reason",
    "Claim Series Number",
    "Source Number",
    "Source Filename",
    "Source Full Path",
    "Extracted DOCTYPE",
    "Destination Number",
    "Destination Filename",
    "Destination Full Path",
    "Destination DOCTYPE",
    "Timestamp",
]

# fill, font colours per status (Excel's standard Good/Bad/Neutral palette)
_STATUS_STYLES: dict[str, tuple[str, str]] = {
    STATUS_MATCH: ("C6EFCE", "006100"),
    STATUS_MISMATCH: ("FFC7CE", "9C0006"),
    STATUS_REVIEW: ("FFEB9C", "9C6500"),
    STATUS_UNEXPECTED: ("FFC7CE", "9C0006"),  # error-highlighted like MISMATCH
}


def build_doctype_audit_excel(
    results: list[AuditResult], out_path: Path
) -> Path:
    """Write the audit Excel report (summary + colored detail rows)."""
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill
    from openpyxl.utils import get_column_letter

    workbook = Workbook()
    ws = workbook.active
    ws.title = "DOCTYPE AUDIT"

    total = len(results)
    match_count = sum(1 for r in results if r.status == STATUS_MATCH)
    mismatch_count = sum(1 for r in results if r.status == STATUS_MISMATCH)
    review_count = sum(1 for r in results if r.status == STATUS_REVIEW)
    unexpected_count = sum(1 for r in results if r.status == STATUS_UNEXPECTED)

    # -- summary section ------------------------------------------------
    ws["A1"] = "DOCTYPE SOURCE-DESTINATION AUDIT"
    ws["A1"].font = Font(bold=True, size=14)
    ws["A2"] = f"TOTAL RECORDS: {total}"
    ws["A3"] = f"MATCH: {match_count}"
    ws["A3"].font = Font(bold=True, color="006100")
    ws["A4"] = f"MISMATCH: {mismatch_count}"
    ws["A4"].font = Font(bold=True, color="9C0006")
    ws["A5"] = f"REVIEW: {review_count}"
    ws["A5"].font = Font(bold=True, color="9C6500")
    ws["A6"] = f"UNEXPECTED DESTINATION: {unexpected_count}"
    ws["A6"].font = Font(bold=True, color="9C0006")

    # -- header row -------------------------------------------------------
    header_row = 8
    for col, name in enumerate(_REPORT_COLUMNS, start=1):
        cell = ws.cell(row=header_row, column=col, value=name)
        cell.font = Font(bold=True)
        cell.fill = PatternFill(
            start_color="D9D9D9", end_color="D9D9D9", fill_type="solid"
        )

    # -- data rows --------------------------------------------------------
    for offset, result in enumerate(results):
        row = header_row + 1 + offset
        values = [
            result.status,
            result.reason,
            result.claim_series_number,
            result.source_number,
            result.source_filename,
            result.source_full_path,
            result.extracted_doctype,
            result.destination_number,
            result.destination_filename,
            result.destination_full_path,
            result.destination_doctype,
            result.timestamp,
        ]
        for col, value in enumerate(values, start=1):
            cell = ws.cell(row=row, column=col, value=value)
            if col == 1 and result.status in _STATUS_STYLES:
                fill_color, font_color = _STATUS_STYLES[result.status]
                cell.fill = PatternFill(
                    start_color=fill_color, end_color=fill_color, fill_type="solid"
                )
                cell.font = Font(bold=True, color=font_color)

    # -- layout: freeze header (+summary), auto-filter, widths ------------
    ws.freeze_panes = f"A{header_row + 1}"
    ws.auto_filter.ref = (
        f"A{header_row}:{get_column_letter(len(_REPORT_COLUMNS))}"
        f"{header_row + max(total, 1)}"
    )
    widths = [22, 34, 22, 14, 46, 70, 17, 19, 42, 70, 19, 20]
    for col, width in enumerate(widths, start=1):
        ws.column_dimensions[get_column_letter(col)].width = width

    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    workbook.save(out_path)
    return out_path


def finalize_doctype_audit(
    results: list[AuditResult], out_dir: Path
) -> Optional[Path]:
    """Build the final audit Excel (only when results exist) and open it.

    Called ONCE after the entire batch has finished (CLI and GUI both).
    Returns the report path, or None when there is nothing to report
    (e.g. dry runs, where nothing was actually processed in HBSys).
    """
    if not results:
        return None
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / (
        f"doctype_audit_report_{datetime.now():%Y%m%d_%H%M%S}.xlsx"
    )
    build_doctype_audit_excel(results, out_path)
    try:
        os.startfile(out_path)  # default Windows Excel behavior
    except Exception:
        pass  # the report file still exists; opening is best-effort
    return out_path


# -- standalone test (AGENTS.md: every module must support __main__) -------

if __name__ == "__main__":
    import tempfile

    failures = 0

    def check(label: str, ok: bool) -> None:
        global failures
        if not ok:
            failures += 1
        print(f"{'OK  ' if ok else 'FAIL'} {label}")

    # normalize_doctype / normalize_sequence (task §21)
    check(
        "normalize: doctype strip/upper/None",
        normalize_doctype(" csf ") == "CSF"
        and normalize_doctype(None) == ""
        and normalize_doctype("CF4") == "CF4",
    )
    check(
        "normalize: sequence '01' == '1' == 1",
        normalize_sequence("01") == normalize_sequence("1")
        == normalize_sequence(1)
        and normalize_sequence(" 07 ") == normalize_sequence("7")
        and normalize_sequence(None) == "",
    )

    # Destination filename parsing (task §10-§11) — generic, no vocab
    check(
        "parse: DOH-PDFA-1b-RAW-CF4-08.pdf -> CF4/08",
        parse_destination_filename("DOH-PDFA-1b-RAW-CF4-08.pdf") == ("CF4", "08", True),
    )
    check(
        "parse: DOH-PDFA-1b-RAW-CSF-01.pdf -> CSF/01",
        parse_destination_filename("DOH-PDFA-1b-RAW-CSF-01.pdf") == ("CSF", "01", True),
    )
    check(
        "parse: DOH-PDFA-1b-RAW-SOA-07.pdf -> SOA/07",
        parse_destination_filename("DOH-PDFA-1b-RAW-SOA-07.pdf") == ("SOA", "07", True),
    )
    check(
        "parse: XML extension + 3-digit number + OTH doc type",
        parse_destination_filename("DOH-PDFA-1b-RAW-XYZ-123.xml") == ("XYZ", "123", True)
        and parse_destination_filename("DOH-PDFA-1b-RAW-OTH-07.pdf") == ("OTH", "07", True),
    )
    check(
        "parse: junk/unparseable names -> parsed=False",
        parse_destination_filename("notes.txt") == ("", "", False)
        and parse_destination_filename("DOH-PDFA-1b-RAW.pdf") == ("", "", False)
        and parse_destination_filename("DOH-PDFA-1b-RAW-CSF.pdf") == ("", "", False),
    )

    # Claim series reuse from the existing popup title
    check(
        "claim series: parsed from popup title",
        extract_claim_series_from_title(
            "Attachments for ANDAYA, FERNANDO OROLA - 260907095364"
        ) == "260907095364"
        and extract_claim_series_from_title("") == ""
        and extract_claim_series_from_title("Attachments for X - Y") == "",
    )

    # -- collector: per-series sequencing (task §5, §7) -------------------
    collector = SourceAuditCollector()
    collector.start_series("260909144200")
    collector.add(r"C:\READY\P1\COE.pdf", "COE")
    collector.add(r"C:\READY\P1\CSF.pdf", "CSF")
    collector.start_series("260909143281")
    collector.add(r"C:\READY\P2\COE.pdf", "COE")
    seqs_a = [r.source_number for r in collector.records[:2]]
    rec_b = collector.records[2]
    check(
        "collector: sequence resets per claim series (01,02 | 01)",
        seqs_a == ["01", "02"] and rec_b.source_number == "01"
        and rec_b.claim_series_number == "260909143281"
        and collector.records[0].claim_series_number == "260909144200",
    )
    check(
        "collector: timestamps + filenames captured",
        all(r.timestamp for r in collector.records)
        and collector.records[0].source_filename == "COE.pdf",
    )

    # -- audit against synthetic destination folders -----------------------
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        series = "260909144200"

        def make_sources(
            c: SourceAuditCollector, docs: list[str]
        ) -> SourceAuditCollector:
            for i, doc in enumerate(docs, start=1):
                c.add(rf"C:\READY\P1\file{i}_{doc}.pdf", doc)
            return c

        # TEST 7 baseline — full 10-document perfect match
        dest = root / series
        dest.mkdir()
        names = [
            "DOH-PDFA-1b-RAW-CSF-01.pdf", "DOH-PDFA-1b-RAW-CSF-02.pdf",
            "DOH-PDFA-1b-RAW-DTR-03.pdf", "DOH-PDFA-1b-RAW-MRF-04.pdf",
            "DOH-PDFA-1b-RAW-PBC-05.pdf", "DOH-PDFA-1b-RAW-SOA-06.pdf",
            "DOH-PDFA-1b-RAW-SOA-07.pdf", "DOH-PDFA-1b-RAW-CF4-08.xml",
            "DOH-PDFA-1b-RAW-CF5-09.xml", "DOH-PDFA-1b-RAW-ESA-10.xml",
        ]
        for n in names:
            (dest / n).write_bytes(b"x")
        c = SourceAuditCollector()
        c.start_series(series)
        make_sources(c, ["CSF", "CSF", "DTR", "MRF", "PBC", "SOA", "SOA", "CF4", "CF5", "ESA"])
        audit = audit_claim_series(c.records, series, dest_root=root)
        statuses = [r.status for r in audit.results]
        check(
            "TEST 7: 10 documents, all MATCH in processing order",
            len(audit.results) == 10
            and set(statuses) == {STATUS_MATCH}
            and [r.source_number for r in audit.results]
            == [f"{i:02d}" for i in range(1, 11)],
        )
        check(
            "TEST 7: numbers+doctypes paired from destination filename",
            all(
                r.destination_number == r.source_number
                and normalize_doctype(r.destination_doctype)
                == normalize_doctype(r.extracted_doctype)
                for r in audit.results
            ),
        )

        def fresh_series(number: str, files: list[str]) -> Path:
            folder = root / number
            folder.mkdir()
            for n in files:
                (folder / n).write_bytes(b"x")
            return folder

        # TEST 1 — normal match (single doc)
        fresh_series("T1", ["DOH-PDFA-1b-RAW-CSF-01.pdf"])
        c1 = SourceAuditCollector()
        c1.start_series("T1")
        c1.add(r"C:\READY\P1\x-CSF.pdf", "CSF")
        a1 = audit_claim_series(c1.records, "T1", dest_root=root)
        check(
            "TEST 1: 01 CSF vs RAW-CSF-01 -> MATCH",
            len(a1.results) == 1
            and a1.results[0].status == STATUS_MATCH
            and a1.results[0].reason == "",
        )

        # TEST 2 — DOCTYPE mismatch: source 08 CF4 vs destination CF5 at 08
        fresh_series(
            "T2",
            [
                "DOH-PDFA-1b-RAW-CSF-01.pdf", "DOH-PDFA-1b-RAW-CSF-02.pdf",
                "DOH-PDFA-1b-RAW-DTR-03.pdf", "DOH-PDFA-1b-RAW-MRF-04.pdf",
                "DOH-PDFA-1b-RAW-PBC-05.pdf", "DOH-PDFA-1b-RAW-SOA-06.pdf",
                "DOH-PDFA-1b-RAW-SOA-07.pdf", "DOH-PDFA-1b-RAW-CF5-08.xml",
            ],
        )
        c2 = SourceAuditCollector()
        c2.start_series("T2")
        make_sources(c2, ["CSF", "CSF", "DTR", "MRF", "PBC", "SOA", "SOA", "CF4"])
        a2 = audit_claim_series(c2.records, "T2", dest_root=root)
        r2 = a2.results[7]
        check(
            "TEST 2: 08 CF4 vs RAW-CF5-08 -> MISMATCH (DOCTYPE mismatch)",
            r2.status == STATUS_MISMATCH and r2.reason == "DOCTYPE mismatch"
            and r2.source_number == "08" and r2.destination_doctype == "CF5",
        )

        # TEST 3 — number mismatch: source 08 CF4, destination file at 09
        fresh_series("T3", ["DOH-PDFA-1b-RAW-CF4-09.xml"])
        c3 = SourceAuditCollector()
        c3.start_series("T3")
        c3.add(r"C:\READY\P1\x-CF4.pdf", "CF4")
        a3 = audit_claim_series(c3.records, "T3", dest_root=root)
        # the only source is 01; destination carries the CF4 at 09, so
        # source 01 has no 01 destination AND 09 has no source -> both
        # a MISMATCH (not found) and an UNEXPECTED DESTINATION record
        miss01 = [r for r in a3.results if r.source_number == "01"]
        extra09 = [r for r in a3.results if r.status == STATUS_UNEXPECTED]
        check(
            "TEST 3: 08 CF4 but file is RAW-CF4-09 -> MISMATCH (not found)",
            len(miss01) == 1
            and miss01[0].status == STATUS_MISMATCH
            and miss01[0].reason == "Destination file not found"
            and len(extra09) == 1
            and extra09[0].destination_number == "09",
        )

        # TEST 4 — missing destination entirely (no 08 file at all)
        c4 = SourceAuditCollector()
        c4.start_series("T3")
        c4.add(r"C:\READY\P1\x-CF4.pdf", "CF4")
        a4 = audit_claim_series(c4.records, "T3", dest_root=root)
        row = [r for r in a4.results if r.source_number == "01"][0]
        check(
            "TEST 4: source with no destination -> MISMATCH (not found)",
            row.status == STATUS_MISMATCH
            and row.reason == "Destination file not found",
        )

        # TEST 5 — unexpected destination (XYZ-11, no source 11)
        fresh_series(
            "T5", ["DOH-PDFA-1b-RAW-CSF-01.pdf", "DOH-PDFA-1b-RAW-XYZ-11.xml"]
        )
        c5 = SourceAuditCollector()
        c5.start_series("T5")
        c5.add(r"C:\READY\P1\x-CSF.pdf", "CSF")
        a5 = audit_claim_series(c5.records, "T5", dest_root=root)
        unexpected = [r for r in a5.results if r.status == STATUS_UNEXPECTED]
        check(
            "TEST 5: RAW-XYZ-11 without source 11 -> UNEXPECTED DESTINATION",
            len(unexpected) == 1
            and unexpected[0].destination_number == "11"
            and unexpected[0].destination_doctype == "XYZ"
            and unexpected[0].reason
            == "Destination document has no corresponding source record",
        )

        # TEST 6 — duplicate destination number (CSF-01 + DTR-01)
        fresh_series(
            "T6", ["DOH-PDFA-1b-RAW-CSF-01.pdf", "DOH-PDFA-1b-RAW-DTR-01.pdf"]
        )
        c6 = SourceAuditCollector()
        c6.start_series("T6")
        c6.add(r"C:\READY\P1\x-CSF.pdf", "CSF")
        a6 = audit_claim_series(c6.records, "T6", dest_root=root)
        check(
            "TEST 6: duplicate 01 -> MISMATCH (duplicate reason, never silent)",
            a6.results[0].status == STATUS_MISMATCH
            and "Duplicate destination sequence number" in a6.results[0].reason
            and "DOH-PDFA-1b-RAW-DTR-01.pdf" in a6.results[0].reason,
        )

        # TEST 8 — multiple claim series: independent audits
        series_b = "260909143281"
        fresh_series(
            series_b,
            ["DOH-PDFA-1b-RAW-COE-01.pdf", "DOH-PDFA-1b-RAW-CSF-02.pdf"],
        )
        cb = SourceAuditCollector()
        cb.start_series(series_b)
        cb.add(r"C:\READY\P2\COE.pdf", "COE")
        cb.add(r"C:\READY\P2\CSF.pdf", "CSF")
        ab = audit_claim_series(cb.records, series_b, dest_root=root)
        check(
            "TEST 8: second claim series audited independently, all MATCH",
            len(ab.results) == 2 and set(r.status for r in ab.results) == {STATUS_MATCH}
            and ab.results[0].claim_series_number == series_b
            and [r.source_number for r in ab.results] == ["01", "02"],
        )

        # A batch mixing two series audits only its own records
        mixed = audit_claim_series(c.records + cb.records, series, dest_root=root)
        check(
            "TEST 8: mixed batch filters records by claim series",
            all(r.claim_series_number == series for r in mixed.results)
            and len(mixed.results) == 10,
        )

        # Missing series folder -> REVIEW, no crash (task §19)
        cmiss = SourceAuditCollector()
        cmiss.start_series("999999999999")
        cmiss.add(r"C:\READY\P9\COE.pdf", "COE")
        missing = audit_claim_series(cmiss.records, "999999999999", dest_root=root)
        check(
            "missing folder: REVIEW 'Claim Series destination folder not found'",
            missing.folder_missing
            and len(missing.results) == 1
            and missing.results[0].status == STATUS_REVIEW
            and missing.results[0].reason == "Claim Series destination folder not found",
        )

        # Unparseable destination filename -> REVIEW (task §20)
        fresh_series("TU", ["DOH-PDFA-1b-RAW-CSF-01.pdf", "readme.txt"])
        c7 = SourceAuditCollector()
        c7.start_series("TU")
        c7.add(r"C:\READY\P1\x-CSF.pdf", "CSF")
        a7 = audit_claim_series(c7.records, "TU", dest_root=root)
        unparsed = [r for r in a7.results if r.status == STATUS_REVIEW]
        check(
            "unparseable destination: REVIEW 'Unable to parse destination filename'",
            len(unparsed) == 1
            and unparsed[0].destination_filename == "readme.txt"
            and unparsed[0].reason == "Unable to parse destination filename",
        )

        # scan_destination_folder: nonexistent folder -> None (no crash)
        check(
            "scan: nonexistent folder -> None",
            scan_destination_folder(root / "nope") is None,
        )

        # -- Excel report (task §23-§27) ---------------------------------
        c_excel = SourceAuditCollector()
        c_excel.start_series(series)
        make_sources(c_excel, ["CSF", "CSF", "DTR", "MRF", "PBC", "SOA", "SOA", "CF4", "CF5", "ESA"])
        report_results = audit_claim_series(
            c_excel.records, series, dest_root=root
        ).results
        report = Path(tmp) / "audit.xlsx"
        build_doctype_audit_excel(report_results, report)
        check("excel: report file created", report.is_file())

        from openpyxl import load_workbook

        wb = load_workbook(report)
        ws = wb.active
        check(
            "excel: summary counts correct",
            ws["A2"].value == f"TOTAL RECORDS: {len(report_results)}"
            and ws["A3"].value == f"MATCH: {len(report_results)}"
            and ws["A4"].value == "MISMATCH: 0"
            and ws["A5"].value == "REVIEW: 0"
            and ws["A6"].value == "UNEXPECTED DESTINATION: 0",
        )
        check(
            "excel: header row frozen + auto-filter",
            ws.freeze_panes == "A9"
            and ws.auto_filter.ref is not None
            and ws.auto_filter.ref.startswith("A8"),
        )
        check(
            "excel: 12 columns incl. Reason/Destination fields, no OCR columns",
            [ws.cell(row=8, column=i).value for i in range(1, 13)]
            == _REPORT_COLUMNS
            and "Actual Selected DOCTYPE" not in _REPORT_COLUMNS
            and not any(
                "OCR" in str(ws.cell(row=8, column=i).value or "")
                for i in range(1, 13)
            ),
        )
        check(
            "excel: MATCH rows colored green",
            ws.cell(row=9, column=1).fill.start_color.rgb == "00C6EFCE",
        )
        # A mixed-status report: MISMATCH red, REVIEW yellow, UNEXPECTED red
        mixed_dest = root / "260909150000"
        mixed_dest.mkdir()
        (mixed_dest / "DOH-PDFA-1b-RAW-CSF-01.pdf").write_bytes(b"x")
        (mixed_dest / "DOH-PDFA-1b-RAW-CF5-02.xml").write_bytes(b"x")
        (mixed_dest / "DOH-PDFA-1b-RAW-XYZ-09.pdf").write_bytes(b"x")
        (mixed_dest / "broken-name.pdf").write_bytes(b"x")
        cm = SourceAuditCollector()
        cm.start_series("260909150000")
        cm.add(r"C:\READY\P3\a-CSF.pdf", "CSF")
        cm.add(r"C:\READY\P3\b-CF4.xml", "CF4")
        am = audit_claim_series(cm.records, "260909150000", dest_root=root)
        mixed_report = Path(tmp) / "mixed.xlsx"
        build_doctype_audit_excel(am.results, mixed_report)
        wb2 = load_workbook(mixed_report)
        ws2 = wb2.active
        check(
            "excel: mixed statuses colored (red/yellow/red-error)",
            ws2.cell(row=9, column=1).fill.start_color.rgb == "00C6EFCE"
            and ws2.cell(row=10, column=1).fill.start_color.rgb == "00FFC7CE"
            and ws2.cell(row=11, column=1).fill.start_color.rgb == "00FFC7CE"
            and ws2.cell(row=12, column=1).fill.start_color.rgb == "00FFEB9C"
            and ws2["A3"].value == "MATCH: 1"
            and ws2["A4"].value == "MISMATCH: 1"
            and ws2["A5"].value == "REVIEW: 1"
            and ws2["A6"].value == "UNEXPECTED DESTINATION: 1",
        )
        # finalize: empty results -> no report; results -> report (+ open
        # is best-effort and suppressed here to avoid spawning Excel)
        check(
            "finalize: no results -> None",
            finalize_doctype_audit([], Path(tmp)) is None,
        )

    print("RESULT:", "PASSED" if failures == 0 else f"{failures} FAILURE(S)")
    raise SystemExit(0 if failures == 0 else 1)
